### ISSUE TITLE
Missing code/html view for TinyMCE in FT 3

### ISSUE THREAD

**Issue by gummisko** [formtools/module-field_type_tinymce#1]
Hello,

In previous FT version the TinyMCE-field editor had the possibility to switch to actual html source-code, which was a great option. Is it possible to add this for FT3?

If not, in the doc it is said: "The tinyMCE is no longer the only possible WYSIWYG field type. Depending on user requirements, we can add additional WYSIWYG modules for scripts like FCKEditor or htmlarea. Anything goes!". Is there a way to integrate any of the mentioned editors?

Thank you!

Gerard

**Comment by gummisko** [comment]
@benkeen 

Hi Ben, actually It seems like something is not working as it should. When I inspect the source of TinyMCE (index.php and code/module.class.php) I notice the 'code' option is set for _expert_ and _advanced_, but this does not appear in the actual editor. 
I am sorry for not being able to figure it out myself.

Regards

Gerard

**Comment by benkeen** [comment]
Hey @gummisko, thanks! Yeah this looks like a bug - `code` is definitely set so it should appear. 

I should get some time this Sunday to look at this,

**Comment by benkeen** [comment]
Fixed in 2.0.7. Will release new version tonight.
